server:
  port: 7001


#Eureka配置
eureka:
  instance:
    hostname: eureka7001.com #Eureka服务端的实例名称
  client:
    server:
      enable-self-preservation: false
      eviction-interval-timer-in-ms: 5000
    registerWithEureka: false  #表示是否向eureka注册中心注册自己
    fetchRegistry: false    #表示fetch-registry如果为false,表示自己为注册中心
    service-url:
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
       defaultZone: http://root:root@eureka7002.com:7002/eureka/,http://root:root@eureka7003.com:7003/eureka/
#修改下security的默认账号密码
spring:
  security:
    user:
      name: root
      password: root