server:
  port: 8001

#mybatis配置
mybatis:
  type-aliases-package: com.meng.springcloud.pojo
  config-location: classpath:mybatis/mabtis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

#spring的配置
spring:
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC&useSSL=true
    username: root
    password:

#Eureka的配置，服务注册到哪里
eureka:
  client:
#    register-with-eureka: false
#    fetch-registry: false
    service-url:
#      defaultZone: http://root:root@localhost:7001/eureka/
#      defaultZone: http://root:root@localhost:7002/eureka/
      defaultZone: http://root:root@eureka7001.com:7001/eureka,http://root:root@eureka7002.com:7002/eureka,http://root:root@eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-provider-dept8001 #修改eureka上的默认描述信息!


#info配置 也就是配置actuator监控页面自己提供的一些信息
info:
  app.name: meng-springcloud
  company.name: blog.meng.com